# Generated by Django 4.1.2 on 2022-10-11 00:42

import advocates.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advocates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profile_pic', models.ImageField(unique=True, upload_to='')),
                ('short_bio', models.CharField(max_length=255, null=True)),
                ('long_bio', models.TextField(blank=True, null=True)),
                ('advocate_years_exp', models.IntegerField(null=True, validators=[advocates.models.number_validator])),
                ('links', models.JSONField(default=advocates.models.linksCallable)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advocates', to='companies.companies')),
            ],
            options={
                'db_table': 'advocates',
            },
        ),
    ]
