# Generated by Django 4.1.2 on 2022-10-09 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advocates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profile_pic', models.ImageField(upload_to='')),
                ('short_bio', models.CharField(max_length=255)),
                ('long_bio', models.TextField(blank=True, null=True)),
                ('advocate_years_exp', models.IntegerField()),
            ],
            options={
                'db_table': 'advocates',
            },
        ),
    ]
