# Generated by Django 4.1.2 on 2022-10-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocates',
            name='profile_pic',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='advocates',
            name='short_bio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
