# Generated by Django 4.1.2 on 2022-10-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocates',
            name='links',
            field=models.JSONField(default={'github': 'github.com/username', 'twitter': 'twitter.com/username', 'youtube': 'youtube.com/username'}),
        ),
    ]
