# Generated by Django 4.1.2 on 2022-10-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0003_advocates_company_alter_advocates_advocate_years_exp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocates',
            name='company',
            field=models.JSONField(default={'href': '/companies/6', 'id': 6, 'logo': 'agora_logo.png', 'name': 'Agora'}),
        ),
    ]
