# Generated by Django 4.1.2 on 2022-10-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0005_alter_advocates_company_alter_advocates_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocates',
            name='company',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='advocates',
            name='links',
            field=models.JSONField(),
        ),
    ]
